/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgnew;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;


/**
 *
 * @author nattachar
 */
public class End extends javax.swing.JFrame {
    
    private int n;
    /**
     * Creates new form End
     */
    public End() {
         initComponents();
         setLocation (400,100);
         setSize(800,600);
         
      
     
    }
    public void init(int n){
        LastScore.setText("SCORE : "+n);
    }
   
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LastScore = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Replay = new javax.swing.JButton();
        Exit2 = new javax.swing.JButton();
        jlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        LastScore.setFont(new java.awt.Font("Tempus Sans ITC", 3, 48)); // NOI18N
        getContentPane().add(LastScore);
        LastScore.setBounds(240, 250, 350, 100);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgnew/replay.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(270, 360, 290, 120);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgnew/exit2.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(270, 460, 290, 110);

        Replay.setText("jButton1");
        Replay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReplayActionPerformed(evt);
            }
        });
        getContentPane().add(Replay);
        Replay.setBounds(320, 390, 120, 60);

        Exit2.setText("jButton2");
        Exit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit2ActionPerformed(evt);
            }
        });
        getContentPane().add(Exit2);
        Exit2.setBounds(330, 490, 110, 60);

        jlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgnew/bg_gameover.jpg"))); // NOI18N
        getContentPane().add(jlabel);
        jlabel.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReplayActionPerformed
        Start s = new Start();
        s.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_ReplayActionPerformed

    private void Exit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Exit2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(End.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(End.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(End.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(End.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new End().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit2;
    private javax.swing.JLabel LastScore;
    private javax.swing.JButton Replay;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jlabel;
    // End of variables declaration//GEN-END:variables
}
